version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: "oscarfonts/h2"
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -web -webAllowOthers